### ISSUE TITLE
GetSocial: add Push Notifications support

### ISSUE THREAD

**Issue by pinchukdiana** [Tardis-x/Bigger-Inside#15]
It will be an amazing tool for reaching our users and letting them know about important updates immediately.
Android setup is super easy, just put Server key and Sender ID into the dashboard 
https://docs.getsocial.im/guides/social-notifications/android/#setup-android-push-notifications
iOS is a bit more complicated, it requires uploading certificates
https://docs.getsocial.im/guides/social-notifications/ios/#setup-ios-push-notifications

**Comment by HubalOleg** [comment]
Done for Android!

**Comment by HubalOleg** [comment]
Done for iOS
