### ISSUE TITLE
Quest: Android back button doesn't navigate to the previous screen

### ISSUE THREAD

**Issue by pinchukdiana** [Tardis-x/Bigger-Inside#16]
Maybe it's intended, let me know

**Comment by pinchukdiana** [comment]
Same on Schedule

**Comment by moinm3uw** [comment]
@pinchukdiana which back button? Device back-button or UI back-button?

**Comment by pinchukdiana** [comment]
Device back button

**Comment by munkiki7** [comment]
Android back button now duplicates the functions of top left buttons
