### ISSUE TITLE
Quest: remove scroll when not needed and add info about quest guys

### ISSUE THREAD

**Issue by pinchukdiana** [Tardis-x/Bigger-Inside#18]
http://take.ms/fhY74
Quest guys are expected to sit somewhere around the registration desk

**Comment by moinm3uw** [comment]
@munkiki7  please add to the text: 
Scan special marker from the Quest folks in expo-area. 

Also, is it possible to remove the scroll? Make text smaller in case if it's too big.

**Comment by munkiki7** [comment]
Scrollbar is hidden when not needed. The scrollbar was intended in the design mock-ups.

**Comment by munkiki7** [comment]
- Scan a special marker from Quest guys, sitting near the registration desk

**Comment by pinchukdiana** [comment]
Updated scroll looks a bit strange: it's too small so it looks like there is a very long content to scroll. In fact, there are only 2 rows of text below  http://take.ms/cLYRp

**Comment by munkiki7** [comment]
Fixed the scroll size
