### ISSUE TITLE
AR Map requires login and that's incorrect

### ISSUE THREAD

**Issue by pinchukdiana** [Tardis-x/Bigger-Inside#19]
AR Map could be used without a login

**Comment by moinm3uw** [comment]
it is a requirement :)

**Comment by pinchukdiana** [comment]
From who? It's against UX to ask for login when not needed

**Comment by moinm3uw** [comment]
@pinchukdiana 
AR Map and Schedule should be available without login

**Comment by pinchukdiana** [comment]
Sorry, seems I used the incorrect word in the beginning: `could` instead of `should`. @h4rdmol  or you placed a comment as a proof to my words?

What do I mean: currently AR Map requires login and that's incorrect.
Expected behavior: Login is not required for AR Map.

**Comment by moinm3uw** [comment]
@pinchukdiana oh... it's misunderstanding :) could you please update the issue title? It can confuse a bit.

Seems like this is a more clear title. 
> AR Map requires login and that's incorrect.

**Comment by HubalOleg** [comment]
Done
