### ISSUE TITLE
UI: different size of user avatar

### ISSUE THREAD

**Issue by pinchukdiana** [Tardis-x/Bigger-Inside#20]
Home screen: avatar is small
Quest: avatar becomes bigger
http://take.ms/qo0Vc
Schedule: avatar is absent (maybe let's add it?)

**Comment by moinm3uw** [comment]
@BruSD please make avatar same as we have on the Quest pages. 
Also, add it to the schedule please

**Comment by ozasadnyy** [comment]
Взагалі беріть шрифти як там, бо бачу ви Open Sans використовуєте, а не Product Sans

**Comment by HubalOleg** [comment]
done

**Comment by HubalOleg** [comment]
Bug reproduces on different screen sizes
