### ISSUE TITLE
Sign in: update the text

### ISSUE THREAD

**Issue by pinchukdiana** [Tardis-x/Bigger-Inside#21]
Current version:
`You need to sign in to be able to play Quest and see the leaderboard. Also, it will have some integration with other demos`

Updated version (added missing article, plural form and clarification what is 'it'):

You need to sign in to be able to play **the** Quest and see the leaderboard. 
Also, **the app** will have some **integrations** with other demos

**Comment by moinm3uw** [comment]
@munkiki7

**Comment by HubalOleg** [comment]
done
