### ISSUE TITLE
Different avatar size in App and quest

### ISSUE THREAD

**Issue by ozasadnyy** [Tardis-x/Bigger-Inside#26]
I prefer quest size
![image](https://user-images.githubusercontent.com/2954281/45648493-6af25e00-bad1-11e8-9fb2-74e827b9b3c8.png)

**Comment by pinchukdiana** [comment]
@ozasadnyy  it's a duplicate to https://github.com/Tardis-x/Bigger-Inside/issues/20

**Comment by pinchukdiana** [comment]
not actually, but let's keep avatar issues in one task
