### ISSUE TITLE
Need to implement User Management  GetSocial 

### ISSUE THREAD

**Issue by BruSD** [Tardis-x/Bigger-Inside#5]
Need to implement User Management, so we can see the users names in the feed, not just ‘User 12652’. 
Intro https://docs.getsocial.im/guides/user-management/introduction/ 
How to add user identity
https://docs.getsocial.im/guides/user-management/unity/managing-user-identities/ 
Hot to change name and avatar
https://docs.getsocial.im/guides/user-management/unity/get-set-user-properties/#change-user-name-or-avatar

**Comment by HubalOleg** [comment]
Done
